services:
  # Backend API Service
  - type: web
    name: notebooklm-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: notebooklm-db
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: vector-index
      - key: MAX_FILE_SIZE
        value: 50000000
      - key: UPLOAD_PATH
        value: ./uploads

  # Frontend Static Site
  - type: static
    name: notebooklm-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: notebooklm-backend
          property: host
        value: https://notebooklm-backend.onrender.com/api

# Database
databases:
  - name: notebooklm-db
    databaseName: notebooklm
    user: notebooklm_user
    plan: starter